export interface CDSOptionModel {
  Id: number;
  AccountId: number;
  TradeDate: Date | null;
  TradeNameId: number;
  SettlementDate: Date | null;
  ISINId: number | null;
  CapitalAllocation: number | null;
  SecurityID: string;
  Description: string;
  TradePrice: number | null;
  TraderRationale: string;
  TradarAccount: string | null;
  TradarPayAccount: string | null;
  FinUpdateTime: Date | null;
  CurrencyId: number | null;
  Notional: number | null;
  EnteredById: number | null;
  CounterPartyId: number | null;

  // ----------------- CDSOption Fields -----------------
  TradeId: number;
  StrikeRate: number | null;
  Upfront: number | null;
  UpfrontDate: Date | null;
  UpfrontCCY: string | null;
  PayFreq: string | null;
  TradeAction: string | null;
  DayCount: string | null;
  FirstCouponDate: Date | null;
  REDCode: string | null;
  AccruedInterest: number | null;
  UnderlyingISIN: string | null;
  IndeptAmt: number | null;
  IndeptCCY: string | null;
  OptionType: string | null;
  OptionStyle: string | null;
  ExchangeRate: number | null;
  Spread: number | null;
  CDSIndexName: string | null;
  SettlementType: string | null;
  OptionExpiryDate: Date | null;
  BenchmarkIndex: string | null;
  MaturityDate: Date;
  CountryId: number | null;
  BBGType: string | null;
  AssetQuality: string | null;
  UtiId: string | null;
  UtiPrefix: string | null;
  FixedRate: string | null;
}